#You need at add energy_info.yaml to your configuration.yaml
---
sensor:
  - platform: homeassistant
    id: daily_net_import
    entity_id: sensor.mp2_energie_soutiree_du_reseau_par_jour
    internal: true
    on_value:
      then:
        - lvgl.label.update:
            id: daily_imported_watts
            text:
              format: "%.1f"
              args: [ 'id(daily_net_import).state' ]

  - platform: homeassistant
    id: daily_net_export
    entity_id: sensor.mp2_energie_injectee_ds_reseau_par_jour
    internal: true
    on_value:
      then:
        - lvgl.label.update:
            id: daily_exported_watts
            text:
              format: "%.1f"
              args: [ 'id(daily_net_export).state' ]

  - platform: homeassistant
    id: daily_solar_energy_production
    entity_id: sensor.mp2_total_energie_produite_jour
    internal: true
    on_value:
      then:
        - lvgl.label.update:
            id: daily_solar_production_watts
            text:
              format: "%.1f"
              args: [ 'id(daily_solar_energy_production).state' ]

  - platform: homeassistant
    id: daily_consumption
    entity_id: sensor.mp2_energy_conso_ac_l1_jour
    internal: true
    on_value:
      then:
        - lvgl.label.update:
            id: daily_consumption_watts
            text:
              format: "%.1f"
              args: [ 'id(daily_consumption).state' ]

  - platform: combination
    id: daily_net_sum
    type: linear
    name: "Daily net sum"
    internal: true
    sources:
      - source: daily_net_import
        coeffecient: 1.0
      - source: daily_net_export
        coeffecient: -1.0
    on_value:
      then:
        - lvgl.label.update:
            id: daily_net_watts
            text:
              format: "%.1f"
              args: [ 'id(daily_net_sum).state' ]
        - if:
            condition:
              lambda: return (id(daily_net_sum).state < 0);
            then:
              - lvgl.widget.update:
                  id: daily_net_watts
                  text_color: ep_blue
              - lvgl.image.update:
                  id: daily_net_watts_icon
                  src: up_arrow
            else:
              - lvgl.widget.update:
                  id: daily_net_watts
                  text_color: ep_orange
              - lvgl.image.update:
                  id: daily_net_watts_icon
                  src: down_arrow
                  
#-------------------------------------------
# Graphics and Fonts
#-------------------------------------------
image:
  - file: modules/assets/house.svg
    id: house_icon
    resize: 30x30
    type: RGB565
    transparency: alpha_channel

  - file: modules/assets/grid_icon.svg
    id: grid_icon
    resize: 30x30
    type: RGB565
    transparency: alpha_channel

  - file: modules/assets/produced_icon.svg
    id: produced_icon
    resize: 30x30
    type: RGB565
    transparency: alpha_channel

  - file: modules/assets/down_arrow.svg
    id: down_arrow
    resize: 30x30
    type: RGB565
    transparency: alpha_channel

  - file: modules/assets/up_arrow.svg
    id: up_arrow
    resize: 30x30
    type: RGB565
    transparency: alpha_channel

  - file: modules/assets/arrow_right_gray.svg
    id: arrow_right_gray
    resize: 15x10
    type: RGB565
    transparency: alpha_channel

  - file: modules/assets/arrow_right_blue.svg
    id: arrow_right_blue
    resize: 15x10
    type: RGB565
    transparency: alpha_channel

font:
  - file: "modules/assets/epVisuelt-Regular.ttf"
    id: ep28
    size: 28
    bpp: 8

  - file: "modules/assets/epVisuelt-Regular.ttf"
    id: ep14
    size: 14
    bpp: 8                  