---
# Boot Screen
    widgets:
      - obj:
          id: boot_screen
          layout:
            type: flex
            flex_flow: COLUMN_WRAP
          height: ${screen_height}
          width: ${screen_width}
          text_font: $text_font
          scrollable: false
          bg_color: white
          bg_opa: COVER
          radius: 0
          pad_all: 5
          widgets:
            - image:
                src: boot_logo_90px
                pad_bottom: 10
            - label:
                id: esphome_version_label
                text_color: black
                text:
                  format: "ESPHome Version: %s"
                  args: [ 'id(esphome_version).state.c_str()' ]
            - label:
                text_color: black
                text:
                  format: "Build Date: %s - %s"
                  args: [__DATE__, __TIME__]
            - label:
                id: connected_mac_label
                text_color: black
                text: "MAC Address: Not Connected"
            - label:
                id: ip_address_label
                text_color: black
                text: "IP Address: Not Connected"
            - label:
                id: connected_ssid_label
                text_color: black
                text: "Connected SSID: Not Connected"
            - label:
                id: wifi_signal_db_percent_label
                text_color: black
                text: "WiFi Strength: Not Connected"
            - obj:
               radius: 0
               pad_all: 0
               border_width: 0
               width: ${screen_width}
               flex_grow: 1
               widgets:
                 - button:
                    align: bottom_right
                    x: -10
                    radius: 15
                    width: 100
                    height: 60
                    checkable: true
                    widgets:
                     - label:
                         text_color: white
                         align: center
                         text: "OK"
                    on_press:
                     - lvgl.widget.hide: boot_screen
