---
# Boot Screen
    widgets:
      - obj:
          id: boot_screen
          height: ${screen_height}
          width: ${screen_width}
          scrollable: false
          bg_color: white
          bg_opa: COVER
          radius: 0
          pad_all: 0
          widgets:
            - obj:
                  layout:
                    type: flex
                    flex_flow: COLUMN_WRAP
                  height: ${screen_height}
                  width: ${screen_width}
                  text_font: $text_font
                  scrollable: false
                  pad_all: 2
                  widgets:
                    - image:
                        src: boot_logo_20px
                    - label:
                        id: esphome_version_label
                        text_color: black
                        text:
                          format: "ESPHome Version: %s"
                          args: [ 'id(esphome_version).state.c_str()' ]
                    - label:
                        text_color: black
                        text:
                          format: "Build Date: %s - %s"
                          args: [__DATE__, __TIME__]
                    - label:
                        id: connected_mac_label
                        text_color: black
                        text: "MAC Address: Not Connected"
                    - label:
                        id: ip_address_label
                        text_color: black
                        text: "IP Address: Not Connected"
                    - label:
                        id: connected_ssid_label
                        text_color: black
                        text: "Connected SSID: Not Connected"
                    - label:
                        id: wifi_signal_db_percent_label
                        text_color: black
                        text: "WiFi Strength: Not Connected"
            - button:
                align: bottom_right
                radius: 15
                width: 80
                height: 50
                widgets:
                 - label:
                     text_color: white
                     align: center
                     text: "OK"
                on_press:
                 - lvgl.widget.hide: boot_screen
