substitutions:
  device_name: esp128-clim_ch_sud
  adress_ip: "192.168.0.128"
  time_timezone: "Europe/Paris"
  
esphome:
  name: "esp128-clim-ch-sud"

esp32:
  board: esp32-s3-devkitc-1  
  framework:
    type: arduino

# Enable Home Assistant API
api:

web_server:
  port: 80

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 5min

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-C3-Mini-Test"
    password: "U0q8KVFfsgCX"

captive_portal:
logger:
  baud_rate: 0  # Disable UART logger if using UART0 (pins 1,3)

external_components:
  - source: github://joshbenner/esphome-daikin-s21@main
    components: [ daikin_s21 ]

uart:
  - id: s21_uart
    tx_pin: GPIO3
    rx_pin: GPIO1
    baud_rate: 2400
    data_bits: 8
    parity: EVEN
    stop_bits: 2

# The base UART communication hub.
daikin_s21:
  tx_uart: s21_uart
  rx_uart: s21_uart

climate:
  - platform: daikin_s21
    id: climate_ch_sud
    visual:
      temperature_step: 1.0
    # Optional HA sensor used to alter setpoint.
    room_temperature_sensor: room_temp  # See homeassistant sensor below

sensor:
  - platform: uptime
    type: seconds
    name: "Uptime"
#Etat de la connection

# Optional additional sensors.
  - platform: daikin_s21
    inside_temperature:
      name: "Temperature Unite interieure"
    outside_temperature:
      name: "Temperature Echangeur Exterieure"
    coil_temperature:
      name: "Temperature Serpentin Unite Int"
    fan_speed:
      name: "Vitesse Ventilateur"
  - platform: homeassistant
    id: room_temp
    entity_id: sensor.chambre_sud_temperature
    unit_of_measurement: °C
switch:
  - platform: restart
    name: "Restart"

binary_sensor:
  - platform: status
    name: "Status"