---
esphome:
  on_boot:
    priority: -100
    then:
      - delay: $boot_screen_delay
      - lvgl.widget.hide: boot_screen

api:

logger:
#  level: info
#  logs:
#    i2c.idf: info
#    touchscreen: info
#    scheduler: none

lvgl:
  displays:
    - my_display
