color:
    - id: burnt_sienna
      hex: 'CC5E14'
    - id: very_dark_gray
      hex: '313131'
    - id: ep_orange
      hex: 'F37320'
    - id: ep_blue
      hex: '01B4DE'
    - id: ep_green
      hex: '7ACf38'

      # The grays in order of darkness
    - id: gray50
      hex: 'FAFAFA'
    - id: gray100
      hex: 'F5F5F5'
    - id: gray200
      hex: 'EEEEEE'
    - id: gray300
      hex: 'E0E0E0'
    - id: gray400
      hex: 'BDBDBD'
    - id: gray500
      hex: '9E9E9E'
    - id: gray600
      hex: '757575'
    - id: gray700
      hex: '616161'
    - id: gray800
      hex: '424242'
    - id: gray900
      hex: '212121'

# The standard RGB color table is already in ESPHome!
# RGB color table
# Imported from https://www.rapidtables.com/web/color/RGB_Color.html

# - id: aliceblue
#   hex: 'F0F8FF'
# - id: antiquewhite
#   hex: 'FAEBD7'
# - id: aqua
#   hex: '00FFFF'
# - id: aquamarine
#   hex: '7FFFD4'
# - id: azure
#   hex: 'F0FFFF'
# - id: beige
#   hex: 'F5F5DC'
# - id: bisque
#   hex: 'FFE4C4'
# - id: black
#   hex: '000000'
# - id: blanchedalmond
#   hex: 'FFEBCD'
# - id: blue
#   hex: '0000FF'
# - id: blueviolet
#   hex: '8A2BE2'
# - id: brown
#   hex: 'A52A2A'
# - id: burlywood
#   hex: 'DEB887'
# - id: cadetblue
#   hex: '5F9EA0'
# - id: chartreuse
#   hex: '7FFF00'
# - id: chocolate
#   hex: 'D2691E'
# - id: coral
#   hex: 'FF7F50'
# - id: cornflowerblue
#   hex: '6495ED'
# - id: cornsilk
#   hex: 'FFF8DC'
# - id: crimson
#   hex: 'DC143C'
# - id: cyan
#   hex: '00FFFF'
# - id: darkblue
#   hex: '00008B'
# - id: darkcyan
#   hex: '008B8B'
# - id: darkgoldenrod
#   hex: 'B8860B'
# - id: darkgray
#   hex: 'A9A9A9'
# - id: darkgreen
#   hex: '006400'
# - id: darkkhaki
#   hex: 'BDB76B'
# - id: darkmagenta
#   hex: '8B008B'
# - id: darkolivegreen
#   hex: '556B2F'
# - id: darkorange
#   hex: 'FF8C00'
# - id: darkorchid
#   hex: '9932CC'
# - id: darkred
#   hex: '8B0000'
# - id: darksalmon
#   hex: 'E9967A'
# - id: darkseagreen
#   hex: '8FBC8F'
# - id: darkslateblue
#   hex: '483D8B'
# - id: darkslategray
#   hex: '2F4F4F'
# - id: darkturquoise
#   hex: '00CED1'
# - id: darkviolet
#   hex: '9400D3'
# - id: deeppink
#   hex: 'FF1493'
# - id: deepskyblue
#   hex: '00BFFF'
# - id: dimgray
#   hex: '696969'
# - id: dodgerblue
#   hex: '1E90FF'
# - id: firebrick
#   hex: 'B22222'
# - id: floralwhite
#   hex: 'FFFAF0'
# - id: forestgreen
#   hex: '228B22'
# - id: fuchsia
#   hex: 'FF00FF'
# - id: gainsboro
#   hex: 'DCDCDC'
# - id: ghostwhite
#   hex: 'F8F8FF'
# - id: goldenrod
#   hex: 'DAA520'
# - id: gold
#   hex: 'FFD700'
# - id: gray
#   hex: '808080'
# - id: green
#   hex: '008000'
# - id: greenyellow
#   hex: 'ADFF2F'
# - id: honeydew
#   hex: 'F0FFF0'
# - id: hotpink
#   hex: 'FF69B4'
# - id: indianred
#   hex: 'CD5C5C'
# - id: indigo
#   hex: '4B0082'
# - id: ivory
#   hex: 'FFFFF0'
# - id: khaki
#   hex: 'F0E68C'
# - id: lavender
#   hex: 'E6E6FA'
# - id: lavenderblush
#   hex: 'FFF0F5'
# - id: lawngreen
#   hex: '7CFC00'
# - id: lemonchiffon
#   hex: 'FFFACD'
# - id: lightblue
#   hex: 'ADD8E6'
# - id: lightcoral
#   hex: 'F08080'
# - id: lightcyan
#   hex: 'E0FFFF'
# - id: lightgoldenrodyellow
#   hex: 'FAFAD2'
# - id: lightgray
#   hex: 'D3D3D3'
# - id: lightgreen
#   hex: '90EE90'
# - id: lightpink
#   hex: 'FFB6C1'
# - id: lightsalmon
#   hex: 'FFA07A'
# - id: lightseagreen
#   hex: '20B2AA'
# - id: lightskyblue
#   hex: '87CEFA'
# - id: lightslategray
#   hex: '778899'
# - id: lightsteelblue
#   hex: 'B0C4DE'
# - id: lightyellow
#   hex: 'FFFFE0'
# - id: lime
#   hex: '00FF00'
# - id: limegreen
#   hex: '32CD32'
# - id: linen
#   hex: 'FAF0E6'
# - id: magenta
#   hex: 'FF00FF'
# - id: maroon
#   hex: '800000'
# - id: mediumaquamarine
#   hex: '66CDAA'
# - id: mediumblue
#   hex: '0000CD'
# - id: mediumorchid
#   hex: 'BA55D3'
# - id: mediumpurple
#   hex: '9370DB'
# - id: mediumseagreen
#   hex: '3CB371'
# - id: mediumslateblue
#   hex: '7B68EE'
# - id: mediumspringgreen
#   hex: '00FA9A'
# - id: mediumturquoise
#   hex: '48D1CC'
# - id: mediumvioletred
#   hex: 'C71585'
# - id: midnightblue
#   hex: '191970'
# - id: mintcream
#   hex: 'F5FFFA'
# - id: mistyrose
#   hex: 'FFE4E1'
# - id: moccasin
#   hex: 'FFE4B5'
# - id: navajowhite
#   hex: 'FFDEAD'
# - id: navy
#   hex: '000080'
# - id: oldlace
#   hex: 'FDF5E6'
# - id: olive
#   hex: '808000'
# - id: olivedrab
#   hex: '6B8E23'
# - id: orange
#   hex: 'FFA500'
# - id: orangered
#   hex: 'FF4500'
# - id: orchid
#   hex: 'DA70D6'
# - id: palegoldenrod
#   hex: 'EEE8AA'
# - id: palegreen
#   hex: '98FB98'
# - id: paleturquoise
#   hex: 'AFEEEE'
# - id: palevioletred
#   hex: 'DB7093'
# - id: papayawhip
#   hex: 'FFEFD5'
# - id: peachpuff
#   hex: 'FFDAB9'
# - id: peru
#   hex: 'CD853F'
# - id: pink
#   hex: 'FFC0CB'
# - id: plum
#   hex: 'DDA0DD'
# - id: powderblue
#   hex: 'B0E0E6'
# - id: purple
#   hex: '800080'
# - id: rebeccapurple
#   hex: '663399'
# - id: red
#   hex: 'FF0000'
# - id: rosybrown
#   hex: 'BC8F8F'
# - id: royalblue
#   hex: '4169E1'
# - id: saddlebrown
#   hex: '8B4513'
# - id: salmon
#   hex: 'FA8072'
# - id: sandybrown
#   hex: 'F4A460'
# - id: seagreen
#   hex: '2E8B57'
# - id: seashell
#   hex: 'FFF5EE'
# - id: sienna
#   hex: 'A0522D'
# - id: silver
#   hex: 'C0C0C0'
# - id: skyblue
#   hex: '87CEEB'
# - id: slateblue
#   hex: '6A5ACD'
# - id: slategray
#   hex: '708090'
# - id: snow
#   hex: 'FFFAFA'
# - id: springgreen
#   hex: '00FF7F'
# - id: steelblue
#   hex: '4682B4'
# - id: tan
#   hex: 'D2B48C'
# - id: teal
#   hex: '008080'
# - id: thistle
#   hex: 'D8BFD8'
# - id: tomato
#   hex: 'FF6347'
# - id: turquoise
#   hex: '40E0D0'
# - id: violet
#   hex: 'EE82EE'
# - id: wheat
#   hex: 'F5DEB3'
# - id: white
#   hex: 'FFFFFF'
# - id: whitesmoke
#   hex: 'F5F5F5'
# - id: yellow
#   hex: 'FFFF00'
# - id: yellowgreen
#   hex: '9ACD32'
