---
    obj:
      border_width: 0
      pad_all: 0
      bg_opa: TRANSP
      scrollable: false
#      outline_width: 1
#      outline_color: red
    label:
      border_width: 0
      scrollable: false
      text_color: ${text_color}
#      outline_width: 1
#      outline_color: red
    image:
      border_width: 0
      scrollable: false
#      outline_width: 1
#      outline_color: red
    button:
      text_font: $text_font
      checkable: false
      press_lock: false
      scroll_on_focus: true
      radius: 25px
      width: $button_width
      height: $button_height_single
      pad_all: 10px
      shadow_width: 0 # This is required even though the default is supposed to be 0
      bg_color: $button_off_color
      text_color: $label_off_color
