---
sun:
  latitude: !secret latitude
  longitude: !secret longitude
  on_sunset:
    - elevation: -3.5°
      then:
        - select.set:
            id: brightness_mode
            option: "Evening"
  on_sunrise:
    - then:
        - select.set:
            id: brightness_mode
            option: "Day"

time:
  - platform: sntp
    id: system_time
    update_interval: 360min   # Change sync interval from default 5min to 6 hours
    on_time_sync:
      - if: # Updates the last restart time
          condition:
            lambda: 'return id(device_last_restart).state == "";'
          then:
            - text_sensor.template.publish:
                id: device_last_restart
                state: !lambda 'return id(system_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");'
    on_time:
      - seconds: 0
        minutes: $screen_night_minute
        hours: $screen_night_hour
        then:
          - select.set:
              id: brightness_mode
              option: "Night"
      - seconds: 0
        minutes: $screen_day_minute
        hours: $screen_day_hour
        then:
          - select.set:
              id: brightness_mode
              option: "Evening"
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: time_update
