---
wifi:
  networks:
    - ssid: !secret wifi
      password: !secret mdpwifi
  reboot_timeout: 5min
  manual_ip:
    static_ip: 192.168.0.182
    gateway: 192.168.0.254
    subnet: 255.255.255.0

web_server:
  port: 80
  version: 3

ota:
  platform: esphome
