substitutions:
  name: jsy194
  current_address: '1'
  current_baud_rate: '9600'
  updates: 2s
  modbus_throttle: 1000ms
  offset_select: '2'
 
esp32:
  board: esp32dev
  framework:
    type: arduino
    version: 2.0.14 #2.0.5 2.0.9
    platform_version: 6.4.0 #4.4.0 6.2.0   
 
esphome:
  name: ${name}
  friendly_name: ${name}
   
# Enable logging
logger:
  #level: debug

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jsy194 Fallback Hotspot"
    password: "OpHFaf5UmP0c"

external_components:
  - source: "github://SeByDocKy/myESPhome/"
    components: [jsy194]
    refresh: 0s

uart:
  - id: uart_0
    tx_pin: GPIO1
    rx_pin: GPIO03 
    baud_rate: ${current_baud_rate}
    stop_bits: 1 # 1 for ESP32, 2 for ESP8266
        
modbus:
   id: modbus_0
   uart_id: uart_0
   send_wait_time: ${modbus_throttle}

button:
  - platform: template
    name: ${name}_reset_energy1
    id: ${name}_reset_energy1
    icon: "mdi:button-pointer"
    on_press:
      then:
        - jsy194.reset_energy1pos: 
           id: ${name}_id
        - delay: 2s
        - jsy194.reset_energy1neg: 
           id: ${name}_id

  - platform: template
    name: ${name}_reset_energy2
    id: ${name}_reset_energy2
    icon: "mdi:button-pointer"
    on_press:
      then:
        - jsy194.reset_energy2pos: 
           id: ${name}_id
        - delay: 2s
        - jsy194.reset_energy2neg: 
           id: ${name}_id  

  - platform: template
    name: ${name}_write_register04
    id: ${name}_write_register04
    icon: "mdi:button-pointer"
    on_press:
      then:
        - jsy194.write_com_setting:
            id: ${name}_id
            new_address: !lambda 'return stoi(id(new_address).state);'
            new_baudrate: !lambda |-
              auto index = id(new_baudrate).active_index();
              return uint8_t( index.value() + ${offset_select}  );
          
  - platform: template
    name: ${name}_read_register04
    id: ${name}_read_register04
    icon: "mdi:button-pointer"
    on_press:
      then:
        - lambda: |-
           uint8_t current_address, current_baudrate;
           esphome::jsy194::JSY194 *sen =  id(${name}_id);
           sen->read_register04();
           current_address = sen->get_address();
           auto address = id(new_address).make_call();
           address.set_value(std::to_string(current_address));
           address.perform();
           current_baudrate = sen->get_baudrate();
           auto baudrate = id(new_baudrate).make_call();
           baudrate.set_index(current_baudrate - ${offset_select});
           baudrate.perform();        

text:
  - platform: template
    name: ${name}_new_address
    id: new_address
    optimistic: true
    min_length: 0
    max_length: 3
    mode: text
    initial_value: '   '
    restore_value: false

select:
  - platform: template
    name: ${name}_new_baudrate
    id: new_baudrate
    optimistic: true
    options:
      - '              '
      - '3 - 1200 bauds'
      - '4 - 2400 bauds'
      - '5 - 4800 bauds'
      - '6 - 9600 bauds'
      - '7 - 19200 bauds'
      - '8 - 38400 bauds'
    initial_option: '              '
    restore_value: false

            
sensor:
  - platform: jsy194
    address: ${current_address}
    current1:
      name: ${name}_current1
      accuracy_decimals: 2
    voltage1:
      name: ${name}_voltage1
      accuracy_decimals: 2
    power1:
      name: ${name}_power1
      accuracy_decimals: 2
    frequency1:
      name: ${name}_frequency1
      accuracy_decimals: 2
    power_factor1:
      name: ${name}_power_factor1
      accuracy_decimals: 2
    pos_energy1:
      name: ${name}_pos_energy1
      accuracy_decimals: 1
    neg_energy1:
      name: ${name}_neg_energy1
      accuracy_decimals: 1

    current2:
      name: ${name}_current2
      accuracy_decimals: 2
    voltage2:
      name: ${name}_voltage2
      accuracy_decimals: 2
    power2:
      name: ${name}_power2
      unit_of_measurement: W
      accuracy_decimals: 2
    frequency2:
      name: ${name}_frequency2
      accuracy_decimals: 2
    power_factor2:
      name: ${name}_power_factor2
      accuracy_decimals: 2
    pos_energy2:
      name: ${name}_pos_energy2
      accuracy_decimals: 1
    neg_energy2:
      name: ${name}_neg_energy2
      accuracy_decimals: 1     
    update_interval: ${updates}
    modbus_id: modbus_0
    id: ${name}_id