# Protocole du JSK
# Pince= Intensité Réseau
# Tore= Intensité ECS
uart:
  id: mod_bus
  tx_pin: ${GPIO_tx}   # GPIO17
  rx_pin: ${GPIO_rx}   # GPIO16
  baud_rate: 4800 #38400
  data_bits: 8
  parity: NONE
  stop_bits: 1
  debug:
    direction: BOTH
    dummy_receiver: false
    debug_prefix: "[JSY] "
    after:
      timeout: 100ms
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ':', debug_prefix);


modbus:
  id: modbus1
  uart_id: mod_bus
  send_wait_time: 500ms
  turnaround_time: 200ms
  

modbus_controller:
  - id: jsymk
    address: 0x1
    modbus_id: modbus1
    update_interval: 5s
    command_throttle: 200ms
    max_cmd_retries: 1
    offline_skip_updates: 2

sensor:  


  # Puissance traversant le tore
  - platform: modbus_controller
    modbus_controller_id: jsymk
    id: puecs
    name: "P_ECS JSYMK"
    address: 0x004A
    unit_of_measurement: "W"
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001
      - sliding_window_moving_average:
          window_size: 10
          send_every: 1
    register_count: 1
    response_size: 4
    state_class: measurement
 