substitutions:
  device_name: esp148-spot-ext-cuisine
  adress_ip: "192.168.0.148"
  friendly_name: esp148
  time_timezone: "Europe/Paris"
esphome:
  name: ${device_name} 
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
    - ssid: !secret wifi
      password: !secret mdpwifi
      
  reboot_timeout: 5min
  
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: ${adress_ip}
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.0.254
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

binary_sensor:
#Etat de la connection
  - platform: status
    name: "${friendly_name}_Status"
    
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name}_bp"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "${friendly_name}_Cde_Spot_ext_Cuisine"
    pin: GPIO12
    id: relay
    
  - platform: restart
    name: "${friendly_name} Restart"

status_led:
  pin:
    number: GPIO13
    inverted: yes
   

    