#
# configuration des log
# 
# https://www.home-assistant.io/integrations/logger/

logger:
  default: info
  logs:
# log level for HA core
    homeassistant.core: fatal

# log level for MQTT integration
    homeassistant.components.mqtt: warning

# log level for all python scripts
    homeassistant.components.python_script: warning

# individual log level for this python script
    homeassistant.components.python_script.my_new_script.py: warning

# log level for SmartThings lights
    homeassistant.components.smartthings.light: warning
    
# log level for a custom component
    #custom_components.my_integration: debug
    custom_components.poollab: warning
    
# log level for the `aiohttp` Python package
    aiohttp: error

# log level for both 'glances_api' and 'glances' integration
    homeassistant.components.glances: fatal
    glances_api: fatal
    
#base de données
    homeassistant.components.recorder: warning
    
# RFXCOM
    rfxtrx: warning

# Modbus
    homeassistant.components.modbus: warning
    pymodbus.client: warning

#AutomMower
    custom_components.husqvarna_automower: warning
    custom_components.husqvarna_automower.vacuum: warning
    custom_components.husqvarna_automower.config_flow: warning
    aioautomower: warning