
# Enregistrement Base de Données externe MySql
# https://www.home-assistant.io/integrations/recorder/

recorder:
  db_url: !secret db_mysql
  auto_purge: true
  auto_repack: true
  commit_interval: 15
  purge_keep_days: 14
  include:
    domains:
      - binary_sensor
      - input_boolean
      - input_datetime
      - input_number
      - input_select
      - sensor
      - switch
      - light
      - utility_meter
      - vacuum
      - sun
      - device_tracker
      - weather
      - group   
      - person
      
  exclude:
    domains:
      - camera
      - zone
      - automation
      - cover
      - script
      - pool_pump
      - alarm_control_panel
      - climate
      - persistent_notification

