# Notification dans Telegram 
telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret id_telegram_remy ## remy
      
notify:
  - name: Telegram
    platform: telegram
    chat_id: !secret id_telegram_remy

