
shell_command:
  push_to_github: /homeassistant/gitpush.sh
  turn_off_remote_pc: "ssh -i /config/.ssh/id_rsa_homeassistant -o 'StrictHostKeyChecking=no' homeassistant@192.168.0.62 sudo reboot -h now"
