substitutions:
  device_name: "esp177-esp32-test"
  friendly_name: "esp177"
  adress_ip: "192.168.0.177"
  time_timezone: "Europe/Paris"

esphome:
  name: ${device_name}

    
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  platform: esphome

ethernet:
  type: W5500
  clk_pin: GPIO17
  mosi_pin: GPIO19
  miso_pin: GPIO18
  cs_pin: GPIO21 
  interrupt_pin: GPIO4
  reset_pin: GPIO5
  clock_speed: 15Mhz

#wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

web_server:
  port: 80

# Configuration Bus i2C
i2c:
  sda: 15 
  scl: 22
  scan: true
  id: bus_a

# Configuration UART
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

# Connection sonde(s) de température DS18b20
one_wire:
  - platform: gpio
    pin: GPIO16

# Extension E/S
sx1509:
  - id: sx1509_hub1
    address: 0x3E

# Utilisez la LED bleue de l'appareil comme LED d'état, qui clignotera s'il y a des avertissements (lent) ou des erreurs (rapide)
status_led:
  pin:
    number: GPIO23
    inverted: true

#Etat de la connection
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
# GPIO sur module extension SX1509
  - platform: gpio
    name: "${friendly_name}_E1"
    pin:
      sx1509: sx1509_hub1
      # Use pin number 0 on the SX1509
      number: 0
      mode:
        input: true
        pullup: false
      inverted: false    
  - platform: gpio
    name: "${friendly_name}_E2"
    pin:
      sx1509: sx1509_hub1
      number: 1
      mode:
        input: true
        pullup: false
      inverted: false    
  - platform: gpio
    name: "${friendly_name}_E3"
    pin:
      sx1509: sx1509_hub1
      number: 2
      mode:
        input: true
        pullup: false
      inverted: false   
  - platform: gpio
    name: "${friendly_name}_E4"
    pin:
      sx1509: sx1509_hub1
      number: 3
      mode:
        input: true
        pullup: false
      inverted: false   
  - platform: gpio
    name: "${friendly_name}_E5"
    pin:
      sx1509: sx1509_hub1
      number: 4
      mode:
        input: true
        pullup: false
      inverted: false   
  - platform: gpio
    name: "${friendly_name}_E6"
    pin:
      sx1509: sx1509_hub1
      number: 5
      mode:
        input: true
        pullup: false
      inverted: false   

# Individual outputs
output:
  - platform: sx1509
    sx1509_id: sx1509_hub1
    id: 'sx1509_output'
    pin: 15

sensor:
  - platform: uptime
    name: Uptime Sensor
    update_interval: 10s

  - platform: dallas_temp
    address: 0xbc01a14909646128
    name: "${friendly_name}_temperature_eau"
    id: temp_eau
    update_interval: 10s
    filters:
      - filter_out: 0.0

# Mesure de la pression filtre Entrée ANA 1
  - platform: adc
    pin: GPIO36
    id: pression_filtre
    name: "${friendly_name}_Pression_filtre"
    unit_of_measurement: "Bars"
    update_interval: 60s
    attenuation: 12db
    filters:
      - calibrate_linear:
        - 0.60 -> 0.0
        - 0.87 -> 0.87
# moyenne sur 30 mn + affichage toutes les mn
      - sliding_window_moving_average:
          window_size: 30
          send_every: 1
switch:
  - platform: restart
    name: "${friendly_name} Restart"
 
  - platform: gpio
    name: "${friendly_name} cde_pompe_filtration"
    pin: GPIO32
    id: cde_ppe_filtration

  - platform: gpio
    name: "${friendly_name} cde_ppe_ph-"
    pin: GPIO33
    id: cde_ppe_ph_moins
    interlock: [cde_ppe_ph_plus]

  - platform: gpio
    name: "${friendly_name} cde_ppe_ph+"
    pin: GPIO25
    id: cde_ppe_ph_plus
    interlock: [cde_ppe_ph_moins]

  - platform: gpio
    name: "${friendly_name} cde_eclairage"
    pin: GPIO26
    id: cde_eclairage

  - platform: gpio
    name: "${friendly_name} cde_volet_ouverture"
    pin: GPIO27
    id: cde_volet_ouverture
    interlock: [cde_volet_fermeture]

  - platform: gpio
    name: "${friendly_name} cde_volet_fermeture"
    pin: GPIO14
    id: cde_volet_fermeture
    interlock: [cde_volet_ouverture]

  - platform: gpio
    name: "${friendly_name} cde_ev_eau"
    pin: GPIO12
    id: cde_ev_eau

  - platform: gpio
    name: "${friendly_name} relais8"
    pin: GPIO13
    id: relais8

# Individual binary outputs
  - platform: gpio
    name: "${friendly_name}_Out15"
    id: sx1509_out14
    pin:
      sx1509: sx1509_hub1
      # Use pin number 1 on the SX1509
      number: 14
      # use as output for switch
      mode:
        output: true
      inverted: false
