
substitutions:
  device_name: esp175-triac-router
  friendly_name: esp175
  adress_ip: "192.168.0.175"
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini
  
wifi:
  networks:
    - ssid: !secret wifi_esp
      password: !secret mdpwifi_esp
      priority: 1
    - ssid: !secret wifi
      password: !secret mdpwifi
      priority: 0
  reboot_timeout: 5min

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80
# Utilisez la LED bleue de l'appareil comme LED d'état, qui clignotera s'il y a des avertissements (lent) ou des erreurs (rapide)
status_led:
  pin:
    number: GPIO16
    inverted: true
#sonde Dallas
dallas:
  - pin: GPIO2 #D4
    update_interval: 10s
    
binary_sensor:
#Etat de la connection
  - platform: status
    name: "${friendly_name}_Status"

number:
  - platform: template
    name: "${friendly_name} P Max"
    id: pmax
    optimistic: true
    restore_value: true
    min_value: 50
    max_value: 100
    step: 1

  - platform: template
    name: "${friendly_name} P Min"
    id: pmin
    optimistic: true
    restore_value: true
    min_value: 5
    max_value: 25
    step: 1

  - platform: template
    name: "${friendly_name} T Max"
    id: tmax
    optimistic: true
    restore_value: true
    min_value: 10
    max_value: 70
    step: 1

  - platform: template
    name: "${friendly_name} Sortie_Triac"
    id: striac
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 100
    step: 1
    on_value:
      then:
        - light.turn_on:
            id: gradateur
            brightness: !lambda |-
              return x/100;
    
sensor:
# Sonde Temperature radiateur
  - platform: dallas
    address: 0x82012111efe81d28
    name: "${friendly_name} Temp triac"
    id: temp_triac
    filters:
      - filter_out: NAN
      
############### TEMPLATE  ######################"
# 
  - platform: template
    name: "${friendly_name} Ecs"
    id: _ecs
    icon: mdi:flash
    unit_of_measurement: "%"
    accuracy_decimals: 4

switch:
  - platform: template
    name: "Dimmer"
    id: dimmer
    optimistic: true

  - platform: gpio
    name: "${friendly_name} Relais"
    pin: GPIO5
    id: relais
    
  - platform: restart
    name: "${friendly_name} Restart"

#AC dimmer level 0 à 1-----------------------------------------------------------------------

output:
  - platform: ac_dimmer
    id: ecs
    gate_pin: GPIO13 #D7
    method: leading
    zero_cross_pin:
      number: GPIO14 #D5
      mode:
        input: true
      inverted: yes
    min_power: 0%

light:
  - platform: monochromatic
    name: "${friendly_name}+STriac"
    output: ecs
    id: gradateur
    default_transition_length: 0s


