substitutions:
  device_name: esp131-pzem-chalet 
  friendly_name: esp131-pzem-chalet
  adress_ip: "192.168.0.131"
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini
  
wifi:
  networks:
    - ssid: !secret wifi
      password: !secret mdpwifi
  reboot_timeout: 5min

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0


# Enable logging
logger:
  baud_rate: 0
# Enable Home Assistant API
api:

ota:

# Configuration UART
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
  stop_bits: 1

web_server:
  port: 80
# Utilisez la LED bleue de l'appareil comme LED d'état, qui clignotera s'il y a des avertissements (lent) ou des erreurs (rapide)
status_led:
  pin:
    number: GPIO16
    inverted: true

binary_sensor:
#Etat de la connection
  - platform: status
    name: "${friendly_name}_Status"

sensor:
  - platform: pzemac
    current:
      name: "${friendly_name} Intensité"
    voltage:
      name: "${friendly_name} Tension"
    energy:
      name: "${friendly_name} Energie"
      unit_of_measurement: "kWh"
      filters:
        - multiply: 0.001
    power:
      name: "${friendly_name} Puissance"
      unit_of_measurement: "W"
    update_interval: 30s

switch:
  - platform: gpio
    name: "${friendly_name} ventilo"
    pin: GPIO5
    id: ventilo
    
  - platform: restart
    name: "${friendly_name} Restart"


      