substitutions:
  device_name: esp173-cpt-eau
  adress_ip: "192.168.0.173"
  friendly_name: esp173
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini
  
wifi:
  networks:
    - ssid: !secret wifi
      password: !secret mdpwifi
  reboot_timeout: 5min
  fast_connect: True
  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0
    dns1: 192.168.0.192
    dns2: 192.168.0.37

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

mqtt:
  broker: 192.168.0.86
  on_json_message:
      topic: N/c0619ab1db0d/battery/277/Dc/0/Power
      then:
        - lambda: |-
            if (x.containsKey("value")){
                const float svalue = x["value"];
                id(pu_batteries).publish_state( svalue);
              }


binary_sensor:
#Etat de la connection
  - platform: status
    name: "${friendly_name}_Status"

sensor:

  - platform: template
    name: "${friendly_name} Pu batterie"
    id: pu_batteries
    unit_of_measurement: "W"
    state_class: "measurement"  
    accuracy_decimals: 2



  # USS-HS43TI
  # D4

  - platform: pulse_meter
    pin: D4
    name: "${friendly_name} Cpt Eau General"
    unit_of_measurement: "litre/mn"
    icon: "mdi:water"
    filters:
     - lambda: return (x/(8.1*60-5));
    total:
      name: "${friendly_name} Cpt Eau General Total"
      unit_of_measurement: "m³"
      accuracy_decimals: 3
      device_class: water
      state_class: total_increasing
      filters:
        - lambda: return (x/(8.1*60-5)/1000);

# Informations WI_FI
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "${friendly_name} WiFi Signal dB"
    update_interval: 60s

############### TEMPLATE  ######################"
# 
                    
switch:
  - platform: restart
    name: "${friendly_name} Restart"


