substitutions:
  device_name: esp129-pesage-ph-moins
  adress_ip: "192.168.0.128"
  time_timezone: "Europe/Paris"
  friendly_name: esp129

esphome:
  name: "esp129-esp32-pesage-ph-moins"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable Home Assistant API
api:

web_server:
  port: 80

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 5min

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

captive_portal:
logger:
  baud_rate: 0  # Disable UART logger if using UART0 (pins 1,3)

sensor:
  - platform: uptime
    type: seconds
    name: "${friendly_name} Uptime"

  - platform: hx711
    name: "${friendly_name} poids ph moins"
    dout_pin: 0 # D0
    clk_pin: 1 #D1
    gain: 128
    update_interval: 1s
    accuracy_decimals: 1
    filters:
      - calibrate_linear:
          - -465800 -> 0
          - 1800000 -> 81
    unit_of_measurement: kg

switch:
  - platform: restart
    name: "${friendly_name} Restart"

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"    