substitutions:
  device_name: esp172-esp8266-1-relais-1
  friendly_name: esp172
  adress_ip: "192.168.0.172"
  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini
  
wifi:
  networks:
    - ssid: !secret wifi_esp
      password: !secret mdpwifi_esp
      priority: 1
    - ssid: !secret wifi
      password: !secret mdpwifi
      priority: 0
  reboot_timeout: 5min

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

# Configuration Dallas
dallas:
  - pin: GPIO2 
    update_interval: 10s

# Utilisez la LED bleue de l'appareil comme LED d'état, qui clignotera s'il y a des avertissements (lent) ou des erreurs (rapide)
status_led:
  pin:
    number: GPIO16
    inverted: true

binary_sensor:
  # 3 Entrées logiques permettant de lire des contacts ou des BP
  - platform: gpio
    pin:
      number: GPIO10
      inverted: True
      mode:
        input: true
        pullup: true
    name: "${friendly_name}_bp1"
  - platform: gpio
    pin:
      number: GPIO13
      inverted: True
      mode:
        input: true
        pullup: true
    name: "${friendly_name}_bp2"
  - platform: gpio
    pin:
      number: GPIO14
      inverted: True
      mode:
        input: true
        pullup: true
    name: "${friendly_name}_bp3"

#Etat de la connection
  - platform: status
    name: "${friendly_name}_Status"

sensor:
  # DS18B20
  - platform: dallas
    address: 0xab0321117f919d
    name: "${friendly_name} Temperature"
    id: temp
    
switch:
  # Pilotage du relais
  - platform: gpio
    name: "${friendly_name} Relais"
    pin: GPIO5
    id: relais
