substitutions:
  device_name: esp140-chalet-eth
  adress_ip: "192.168.0.140"
  friendly_name: esp140
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP32
  board: esp-wrover-kit

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "7f5924bc7de9aceb5b6b434afab874c4" # Ne pas supprimer

web_server:
  port: 80

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  
  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0
# Connection sonde(s) de température DS18b20
dallas:
  pin: 32
  update_interval: 10s



sensor:  
  - platform: dallas
    address: 0x82012111efe81d28
    name: "${friendly_name}_temperature_air"
    id: temp_air
#    filters:
#      - filter_out: 0.0


#Etat de la connection
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"


    

    