substitutions:
  device_name: esp174-esp32-eth0-dimmer-ecs
  adress_ip: "192.168.0.174"
  friendly_name: esp174
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP32
  board: wt32-eth01 #esp-wrover-kit

# Enable logging
logger:

# Enable Home Assistant API
api:
ota:
web_server:
  port: 80

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

output:
  - platform: ledc
    pin: GPIO2
    id: pwm_output
    #frequency: 50 Hz

#fan:
#  - platform: speed
#    output: pwm_output
#    name: "Living Room Fan"

light:
  - platform: monochromatic
    output: pwm_output
    name: "Kitchen Light"
sensor:
# Lecture de la consigne de puissance dans HA
  - platform: homeassistant
    name: "${friendly_name} Consigne Puissance Dimmer"
    entity_id: input_number.consigne_dimmer_ecs
    id: p_dimmer
    on_value:
      then:
      - output.ledc.set_frequency:
          id: pwm_output
          frequency: !lambda "return x*100;"
#        - output.set_level:
#            id: pwm_output
#            level: !lambda "return x/1000;"

#Etat de la connection
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"


    

    