substitutions:
  device_name: esp173-cpt-eau
  adress_ip: "192.168.0.173"
  friendly_name: esp173
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini
  platformio_options:
    lib_deps: NeoPixelBus@2.6.0

wifi:
  networks:
    - ssid: !secret wifi
      password: !secret mdpwifi
  reboot_timeout: 5min
  fast_connect: True
  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0
    dns1: 192.168.0.192
    dns2: 192.168.0.37

# Enable logging
logger:
  level: very_verbose
#  logs:
#    wifi.component: debug
#    mqtt.component: debug
# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

mqtt:
  broker: 192.168.0.37
  username: !secret mqtt_ha_name
  password: !secret mqtt_ha_pw


# Led WS2812 RGB  
light:

  - platform: neopixelbus
    method:
      type: esp8266_dma
    num_leds: 5 #1
    pin: RX
    name: "RGB strip"
    variant: 800KBPS
    id: w_led

  - platform: partition
    name: led1
    id: led1
    default_transition_length: 0s
    segments:
      - id: w_led
        from: 0
        to: 0
  - platform: partition
    name: led2
    id: led2
    default_transition_length: 0s
    segments:
      - id: w_led
        from: 1
        to: 1
  - platform: partition
    name: led3
    id: led3
    default_transition_length: 0s
    segments:
      - id: w_led
        from: 2
        to: 2
  - platform: partition
    name: led4
    id: led4
    default_transition_length: 0s
    segments:
      - id: w_led
        from: 3
        to: 3
  - platform: partition
    name: led5
    id: led5
    default_transition_length: 0s
    segments:
      - id: w_led
        from: 4
        to: 4

binary_sensor:
#Etat de la connection
  - platform: status
    name: "${friendly_name}_Status"

sensor:


  # USS-HS43TI
  # D4

  - platform: pulse_meter
    pin: D4
    name: "${friendly_name} Cpt Eau General"
    unit_of_measurement: "litre/mn"
    icon: "mdi:water"
    filters:
     - lambda: return (x/(8.1*60-5));
    total:
      name: "${friendly_name} Cpt Eau General Total"
      unit_of_measurement: "m³"
      accuracy_decimals: 3
      device_class: water
      state_class: total_increasing
      filters:
        - lambda: return (x/(8.1*60-5)/1000);

# Informations WI_FI
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "${friendly_name} WiFi Signal dB"
    update_interval: 60s

############### TEMPLATE  ######################"
# 
                    
switch:
  - platform: restart
    name: "${friendly_name} Restart"


