substitutions:
  device_name: "esp181-ecran-tactile1"
  friendly_name: esp181
  adress_ip: "192.168.0.181"
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  project:
    name: "rem81.esp181-esp32"
    version: "0.0.0"

esp32:
  board: lolin32
  framework:
    type: arduino
    #board: mhetesp32minikit 

wifi:
  networks:
    - ssid: !secret wifi
      password: !secret mdpwifi
  reboot_timeout: 5min

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

# Example configuration entry
web_server:
  port: 80

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  platform: esphome
  
captive_portal:


#psram:
#  mode: octal
#  speed: 80MHz
#Broche VCC de l'écran: sortie 3,3 V de l'ESP32
#Broche GND de l'écran: broche GND de l'ESP32
#Broche CS de l'écran: broche D15 de l'ESP32
#Broche Reset de l'écran: broche D4 de l'ESP32
#Broche DC de l'écran: broche D5 de l'ESP32
#Broche SDI (MOSI) de l'écran: broche D23 de l'ESP32
#Broche SCK de l'écran: broche D18 de l'ESP32
#Broche LED de l'écran: sortie 3,3 V de l'ESP32
#Broche CDCK (MISO) de l'écran: broche D19 de l'ESP32
#Broche T_CLK de l'écran: broche D18 de l'ESP32
#Broche T_CS de l'écran: broche D21 de l'ESP32
#Broche T_DIN de l'écran: broche D23 de l'ESP32
#Broche T_DO de l'écran: broche D19 de l'ESP32
#Broche T_IRQ de l'écran: pas branchée
  
spi:
  clk_pin: 18 # (Pin on display - SCK/T_CLK)
  mosi_pin: 23 # (Pin on display - SDI(MOSI)/T_DIN)
  miso_pin: 19 # (Pin on display - SDO(MISO)/T_DO)
    
# Configuration de l'écran
display:
  - platform: ili9xxx
    model: ILI9341  # ou ST7789V selon votre écran
    cs_pin: 15
    dc_pin: 5
    reset_pin: 4 
    rotation: 90
    invert_colors: false
    dimensions:
      width: 320
      height: 240
    pages:
      - id: page1
        lambda: |-
          it.rectangle(10, 10, 50, 50, Color::WHITE);  // Dessine un rectangle
    update_interval: 1s


# Police intégrée

# Configuration du tactile (optionnel pour ce test)
#touchscreen:
#  platform: xpt2046
#  id: my_touchscreen
#  cs_pin: 21
#  update_interval: 50ms
#  threshold: 400
#  transform:
#    mirror_x: true
#  calibration:
#    x_min: 280
#    x_max: 3860
#    y_min: 340
#    y_max: 3860
#  on_touch:
#    - lambda: |-
#          ESP_LOGD("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
#              touch.x,
#              touch.y,
#              touch.x_raw,
#             touch.y_raw
#             );

# Police pour l'affichage
#font:
#  - file: "fonts/Montserrat-Regular.ttf"
#    id: my_font
#    size: 8  # Réduit pour limiter l'usage mémoire

