substitutions:
  device_name: "esp177-esp32-test"
  friendly_name: "esp177"
  adress_ip: "192.168.0.177"
  time_timezone: "Europe/Paris"

esphome:
  name: ${device_name}

      
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

    
# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0
    dns1: 192.168.0.254    

web_server:
  port: 80

# utilisez la LED de l'appareil comme LED d'état, qui clignotera s'il y a des avertissements (lent) ou des erreurs (rapide)
status_led:
  pin:
    number: GPIO23
    inverted: true

#Etat de la connection
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

sensor:
  - platform: uptime
    name: Uptime Sensor
    update_interval: 10s


switch:
  - platform: restart
    name: "${friendly_name} Restart"
  - platform: gpio
    name: "${friendly_name} Relais"
    pin: GPIO32
    id: relais

 
