substitutions:
  device_name: "esp181-ecran-tactile1"
  friendly_name: esp181
  adress_ip: "192.168.0.181"
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  project:
    name: "rem81.esp181-esp32"
    version: "0.0.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  networks:
    - ssid: !secret wifi
      password: !secret mdpwifi
  reboot_timeout: 5min

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

# Example configuration entry
web_server:
  port: 80

# Enable logging
logger:
  level: VERY_VERBOSE

# Enable Home Assistant API
api:

ota:
  platform: esphome
  
captive_portal:
font:
  - file: "fonts/arial.ttf"
    id: arial
    size: 15
    
psram:
  #mode: octal
  #speed: 80MHz
  
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
    

# Example configuration entry 
time:
  - platform: homeassistant
    id: homeassistant_time

display:
  - platform: ili9xxx  
    model: ili9341    

    rotation: 0
    cs_pin: GPIO15  # Broche CS (Chip Select)
    dc_pin: GPIO05  # Broche DC (Data/Command)
    reset_pin: GPIO04  # Broche de réinitialisation    
    dimensions: 320x240
    update_interval: 10s
    color_order: rgb
    auto_clear_enabled: false
    id: my_display    

lvgl:
  displays:
    - my_display

  pages:
    - id: main_page
      widgets:
        - label:
            align: CENTER
            text: 'Hello World!'