substitutions:
  device_name: esp123-pzem-sdb
  friendly_name: esp131-pzem-chalet
  adress_ip: "192.168.0.123"
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini



wifi:
  networks:
    - ssid: !secret wifi_esp
      password: !secret mdpwifi_esp
      priority: 1
    - ssid: !secret wifi
      password: !secret mdpwifi
      priority: 0
  reboot_timeout: 5min

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0
    
#captive_portal:

# Enable logging
logger:
  baud_rate: 0
  
# Enable Home Assistant API
api:

ota:
  platform: esphome
  
web_server:
  port: 80

# Configuration UART
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
  stop_bits: 1

#Etat de la connection
binary_sensor:
  - platform: status
    name: "esp123_Status"

sensor:
  - platform: pzemac
    current:
      name: "PZEM-SdB Intensite"
    voltage:
      name: "PZEM-SdB Tension"
    energy:
      name: "PZEM-SdB Energie"
      unit_of_measurement: "kWh"
      filters:
        - multiply: 0.001
    power:
      name: "PZEM-SdB Puissance"
      unit_of_measurement: "W"
    frequency:
      name: "PZEM-SdB Frequence"
      unit_of_measurement: "hz"
    power_factor:
      name: "PZEM-SdB FactPuiss"
      unit_of_measurement: "%"      
    update_interval: 30s

switch:
  - platform: restart
    name: "PZEM-SdB Restart"
