substitutions:
  device_name: esp126-temp-ecs
  friendly_name: esp126
  adress_ip: "192.168.0.126"
  time_timezone: "Europe/Paris"

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m  
  
wifi:
  networks:
    - ssid: !secret wifi
      password: !secret mdpwifi
  reboot_timeout: 5min
    
  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

captive_portal:

# Enable logging
logger:
  level: INFO
  
# Enable Home Assistant API
api:

ota:
  platform: esphome
web_server:
  port: 80

#uart:
#  rx_pin: GPIO3 # RX=pin 21
#  tx_pin: GPIO1 # TX=pin 22
#  baud_rate: 9600
# Configuration Dalas
one_wire:
  - platform: gpio  
    pin: GPIO0

#Etat de la connection
binary_sensor:
  - platform: status
    name: "Status"
        
sensor:
  - platform: dallas_temp
    #address: 0xCA00AA2D00000328
    name: "${friendly_name} temp_ecs"
    device_class: temperature
    state_class: "measurement"     
    filters:
      - offset: 2.0


switch:
  - platform: restart
    name: "${friendly_name} Restart"
