substitutions:
  device_name: esp170-esp8266-2-relais
  friendly_name: esp170
  adress_ip: "192.168.0.170"
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
#  platform: ESP8266
#  board: d1_mini

esp8266:
  board: d1_mini
  framework:
    version: recommended
    
wifi:
  networks:
    - ssid: !secret wifi_esp
      password: !secret mdpwifi_esp
      priority: 1
    - ssid: !secret wifi
      password: !secret mdpwifi
      priority: 0
  reboot_timeout: 5min

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

# Utilisez la LED bleue de l'appareil comme LED d'état, qui clignotera s'il y a des avertissements (lent) ou des erreurs (rapide)
status_led:
  pin:
    number: GPIO16
    inverted: true
    
binary_sensor:
#Etat de la connection
  - platform: status
    name: "${friendly_name}_Status"

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal Sensor"
    update_interval: 60s

  - platform: uptime
    name: "${friendly_name} Uptime Sensor"
    update_interval: 60s
    
switch:
  - platform: gpio
    name: "${friendly_name} Relais1"
    pin: GPIO4
    id: relay1
  - platform: gpio
    name: "${friendly_name} Relais2"
    pin: GPIO5
    id: relay2
    
  - platform: restart
    name: "${friendly_name} Restart"

 