substitutions:
  device_name: esp143-test-esp8266
  adress_ip: "192.168.0.143"

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini
  friendly_name: esp143

wifi:
  networks:
    - ssid: !secret wifi_esp
      password: !secret mdpwifi_esp
      priority: 1
    - ssid: !secret wifi
      password: !secret mdpwifi
      priority: 0
  reboot_timeout: 5min

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
   
web_server:
  port: 80

sensor:
  - platform: ntc
    sensor: resistance_sensor
    calibration:
#      - 20.01kOhm -> 25°C
#      - 68.057kOhm -> 0.56°C
#      - 32.336kOhm -> 15°C
      - 298.057kOhm -> 0.56°C
      - 262.336kOhm -> 15°C
      - 250.01kOhm -> 25°C

    name: esp143-ntc20k
    
  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: UPSTREAM
    resistor: 100.0kOhm
    name: Resistance Sensor
    
  - platform: adc
    id: source_sensor
    pin: A0      
    # Added:
    update_interval: 10s
   
#Etat de la connection
binary_sensor:
  - platform: status
    name: "Status"

output:
  - platform: esp8266_pwm
    pin: D1
    frequency: 1000 Hz
    id: pwm_output
