substitutions:
  device_name: esp129-climat-garage
  adress_ip: "192.168.0.129"
  friendly_name: esp129
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
    - ssid: !secret wifi_esp
      password: !secret mdpwifi_esp
      priority: 1
    - ssid: !secret wifi
      password: !secret mdpwifi
      priority: 0
  reboot_timeout: 5min

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

logger:
api:
ota:
web_server:
  port: 80

i2c:
  sda: GPIO00 #
  scl: GPIO02 #
  scan: true
  id: bus_a

#Etat de la connection
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

sensor:
  - platform: htu21d
    temperature:
      name: "${device_name} Temperature"
    humidity:
      name: "${device_name} Humidité"
    update_interval: 60s

