substitutions:
  device_name: esp142-test-esp32
  adress_ip: "192.168.0.142"
  friendly_name: esp142
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
      
esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  networks:
    - ssid: !secret wifi
      password: !secret mdpwifi
  reboot_timeout: 5min

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0
    dns1: 192.168.0.254

# Enable logging
logger:
  baud_rate: 0
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  platform: esphome

web_server:
  port: 80
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Paris
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

sensor:
  - platform: ina219
    address: 0x40
    shunt_resistance: 0.1
    current:
      name: "Courant DC"
      id: courant_dc
      accuracy_decimals: 3
    bus_voltage:
      name: "Tension DC"
      id: tension_dc
      accuracy_decimals: 3
    power:
      name: "Puissance DC"
      id: puissance_dc
      accuracy_decimals: 3
    update_interval: 2s
    

globals:
  - id: affichage_index
    type: int
    initial_value: '0'

interval:
  - interval: 2s
    then:
      - lambda: |-
          id(affichage_index) = (id(affichage_index) + 1) % 3;

display:
  - platform: tm1638
    id: tm_display
    dio_pin: GPIO18
    clk_pin: GPIO17
    stb_pin: GPIO16
    update_interval: 2s
    lambda: |-
      if (id(affichage_index) == 0)
        it.printf("U=%5.3f", id(tension_dc).state);
      else if (id(affichage_index) == 1)
        it.printf("I=%5.3f", id(courant_dc).state);
      else
        it.printf("P=%5.3f", id(puissance_dc).state);
binary_sensor:
#Etat de la connection
  - platform: status
    name: "Status"

switch:
  - platform: restart
    name: "Restart"
