substitutions:
  device_name: esp174-esp32-eth0-dimmer-ecs
  adress_ip: "192.168.0.174"
  friendly_name: esp174
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP32
  board: wt32-eth01 #esp-wrover-kit

# Enable logging
logger:

# Enable Home Assistant API
api:
ota:
web_server:
  port: 80

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

binary_sensor:
#Etat de la connection
  - platform: status
    name: "${friendly_name}_Status"

output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: GPIO2
    zero_cross_pin:
      number: GPIO4
      mode:
        input: true
      inverted: yes


light:
  - platform: monochromatic
    output: dimmer1
    name: "${friendly_name} Puissance Dimmer ECS"

# Restart de l'ESP
switch:   
  - platform: restart
    name: "${friendly_name} Restart"
 


    

    