substitutions:
  device_name: esp140-chalet-eth
  adress_ip: "192.168.0.140"
  friendly_name: esp140
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP32
  board: esp-wrover-kit

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "7f5924bc7de9aceb5b6b434afab874c4" # Ne pas supprimer

web_server:
  port: 80

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  
  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

uart:
  id: mod_bus
  tx_pin: 32
  rx_pin: 33
  baud_rate: 9600
  stop_bits: 1
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      timeout: 150ms
    sequence:
      - lambda: |-
          UARTDebug::log_string(direction, bytes);

modbus:
#flow_control_pin: 5
  #send_wait_time: 200ms
  id: modbus1
  flow_control_pin: 5

modbus_controller:
  - id: afficheur
    ## the Modbus device addr
    address: 0x1
    modbus_id: modbus1
    update_interval: 1s
    command_throttle: 50ms
    # setup_priority: -10
sensor:  

# tension de l'alimentation
  - platform: modbus_controller
    modbus_controller_id: afficheur
    id: _niv_puit
    name: "${friendly_name}_Niveau_Puit"
    address: 0x0001
    unit_of_measurement: "mL"
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 1
    #register_count: 1
    #response_size: 2
    device_class: volume
    state_class: total

# Mesure du niveau
  - platform: adc
    pin: GPIO39 #A0
    id: niveau_eau
    name: "${friendly_name}_niveau_puit"
    unit_of_measurement: "mL"
    device_class: volume
    state_class: total
    update_interval: 60s
    attenuation: 11db
    filters:
      - calibrate_linear:
         - 0.86 -> 0.5  # 4 ma
         - 1.88 -> 3.23  # 12.61
      - sliding_window_moving_average:
          window_size: 10 # moyenne sur x lectures
          send_every: 5 # envoi toutes les x lectures
          send_first_at: 1 # envoi à la premiere lecture

############### TEMPLATE  ######################"
# Calcul volume eau
  - platform: template
    name: "volume_puit"
    id: volume
    icon: mdi:flash
    unit_of_measurement: "m³"
    device_class: volume
    accuracy_decimals: 2
    lambda: |-
      return (id(niveau_eau).state*0.6*0.6*3.14159);
      
  - platform: template
    name: "niveau_remplissage_puit"
    id: niveau
    icon: mdi:flash
    unit_of_measurement: "%"
    accuracy_decimals: 2
    lambda: |-
      return (id(niveau_eau).state/5.8*100);

  - platform: template
    name: "niveau_reserve_puit"
    id: niveau_reserve
    icon: mdi:flash
    unit_of_measurement: "m"
    device_class: distance
    accuracy_decimals: 2
    lambda: |-
      return (5.8-id(niveau_eau).state);

#Etat de la connection
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"


    

    