substitutions:
  device_name: esp133-congel
  adress_ip: "192.168.0.133"
  friendly_name: esp133
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
    - ssid: !secret wifi_esp
      password: !secret mdpwifi_esp
      priority: 1
    - ssid: !secret wifi
      password: !secret mdpwifi
      priority: 0

  reboot_timeout: 5min
  
  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome
web_server:
  port: 80


# Configuration Dallas
one_wire:
  - platform: gpio  
    pin: GPIO0

#Etat de la connection
binary_sensor:
  - platform: status
    name: "${friendly_name}_Status"
    
sensor:
  - platform: dallas_temp
    #address: 0x15006D2B00004B28
    name: "temp_congelo_garage"
