substitutions:
  device_name: esp125-piscine
  friendly_name: esp125
  adress_ip: "192.168.0.125"
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP32
  board: lolin_d32

wifi:
  networks:
    - ssid: !secret wifi_esp
      password: !secret mdpwifi_esp
      priority: 1
    - ssid: !secret wifi
      password: !secret mdpwifi
      priority: 0
  reboot_timeout: 5min

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

# Configuration ESP32
i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a
  
#Etat de la connection
binary_sensor:
  - platform: status
    name: "${friendly_name}_Status"

sensor:
# Mesure du pH
  - platform: ezo
    id: esp125_ph_ezo
    name: ph_ezo
    address: 99
    unit_of_measurement: "pH"
    accuracy_decimals: 2
    update_interval: 60s # Mettre 1 s pour etalonnage attendre 2/3 minutes que la valeur se tabilise
  #  moyenne sur 15 mn-affichage toutes les 5mn
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 5
          send_first_at: 1
  # Etalonné le 28 juin 2023          
      - calibrate_linear:
        - 4.547 -> 4.0
        - 7.282 -> 6.86
        - 9.447 -> 9.18
  # Etalonné le 6 juillet 2022          
  #    - calibrate_linear:
  #      - 4.44 -> 4.0
  #      - 7.17 -> 6.86
  #      - 9.41 -> 9.18


# Mesure de la pression filtre
  - platform: adc
    pin: A0
    id: esp125_pression_filtre
    name: "Pression filtre"
    unit_of_measurement: "Bars"
    update_interval: 60s
    attenuation: 11db
    filters:
      - calibrate_linear:
        - 0.58 -> 0.0
        - 0.82 -> 0.8
# moyenne sur 30 mn + affichage toutes les mn
      - sliding_window_moving_average:
          window_size: 30
          send_every: 1
# Avec le 30PSI
#    filters:
#      - calibrate_linear:
#        - 0.5 -> 0.0
#""        - 2.21 -> 0.8
# moyenne sur 30 mn + affichage toutes les mn
#      - sliding_window_moving_average:
#          window_size: 30
#          send_every: 1

  - platform: homeassistant
    name: "T° Eau Piscine"
    id: temp_piscine
    entity_id: sensor.temp_piscine
   
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal Sensor"
    update_interval: 60s

#  - platform: homeassistant
#    #name: "mode de fonctionnemment"
#    id: mode_f
#    entity_id: input_select.mode_fonctionnement_piscine

# gestion afficheur
display:
  - platform: lcd_pcf8574
    dimensions: 16x2
    address: 0x27
    update_interval: 5s
    lambda: |-
      it.printf(0,0,"Ph=%.2f",id(esp125_ph_ezo).state);
      it.printf(8,0,"P=%.3f",id(esp125_pression_filtre).state);
      it.printf(8,1,"T=%.1f",id(temp_piscine).state);
#it.printf(15,1,"T=%.1s",id(mode_f).state);

switch:
  - platform: restart
    name: "${friendly_name} Restart"