
substitutions:
  device_name: esp175-triac-router
  friendly_name: esp175
  adress_ip: "192.168.0.175"
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini
  
wifi:
  networks:
    - ssid: !secret wifi
      password: !secret mdpwifi
  reboot_timeout: 5min
  fast_connect: True
  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0
    dns1: 192.168.0.192
    dns2: 192.168.0.37

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80


binary_sensor:
#Etat de la connection
  - platform: status
    name: "${friendly_name}_Status"

sensor:  
# Informations WI_FI
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "${friendly_name} WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "${friendly_name} WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
############### TEMPLATE  ######################"
# 
                    
switch:
  - platform: restart
    name: "${friendly_name} Restart"

#AC dimmer level 0 à 1-----------------------------------------------------------------------

output:
  - platform: ac_dimmer
    id: ecs
    gate_pin: GPIO13
    method: leading
    init_with_half_cycle: false
    zero_cross_pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: yes
#    min_power: 0%

light:
  - platform: monochromatic
    name: "${friendly_name}+STriac"
    output: ecs
    id: gradateur
    default_transition_length: 50ms

