substitutions:
  device_name: esp134-mesure-uv
  adress_ip: "192.168.0.134"
  friendly_name: esp124
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

wifi:
  networks:
    - ssid: !secret wifi_esp
      password: !secret mdpwifi_esp
      priority: 1
    - ssid: !secret wifi
      password: !secret mdpwifi
      priority: 0
  reboot_timeout: 5min

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0
    dns1: 192.168.0.254

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome

web_server:
  port: 80

sensor:
#ML8511 Mesure UV en mW/Cm²
  - platform: adc
    pin: A0
    name: "${friendly_name}_uv"
    unit_of_measurement: "UV"
    update_interval: 60s
    accuracy_decimals: 1
    filters:
      - calibrate_linear:
        - 0.31 -> 0.0
        - 0.88 -> 15.0
# moyenne sur 5 mn
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5  

#Etat de la connection
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
