
substitutions:
  device_name: esp175-spot-ext-cuisine
  friendly_name: esp175
  adress_ip: "192.168.0.175"
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
esp8266:
  board: d1_mini
  framework:
    version: recommended  
  
wifi:
  networks:
    - ssid: !secret wifi
      password: !secret mdpwifi
  reboot_timeout: 5min
  fast_connect: True
  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0
    dns1: 192.168.0.214
    dns2: 192.168.0.210

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome
web_server:
  port: 80

# Utilisez la LED bleue de l'appareil comme LED d'état, qui clignotera s'il y a des avertissements (lent) ou des erreurs (rapide)
status_led:
  pin:
    number: GPIO16
    inverted: true

binary_sensor:
#Etat de la connection
  - platform: status
    name: "${friendly_name}_Status"

# 
switch:
  - platform: restart
    name: "${friendly_name}_Restart"

  # Pilotage du relais
  - platform: gpio
    name: "${friendly_name}_Cde-Spot-Ext-Cuisine"
    pin: GPIO5
    id: relais
