substitutions:
  device_name: esp125-frigo
  adress_ip: "192.168.0.125"

esphome:
  name: ${device_name}

esp32:
  board: esp32dev
  
# Enable logging
logger:

api:

ota:
  - platform: esphome

captive_portal:

wifi:
  networks:
    - ssid: !secret wifi_esp
      password: !secret mdpwifi_esp
  reboot_timeout: 5min

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0
    dns1: !secret dns1
    dns2: !secret dns2

web_server:
  port: 80

one_wire:
  - platform: gpio  
    pin: GPIO4 

sensor:
  - platform: dallas_temp
    name: "Température DS18B20"
    id: temp_ds18b20
    device_class: temperature
    state_class: "measurement"
    update_interval: 10s

  - platform: adc
    pin: GPIO34
    id: adc_ctn
    attenuation: 12db
    update_interval: 10s

  - platform: ntc
    sensor: res_ntc
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 20kOhm
    name: "Température CTN"
    id: temp_ctn

  # === CTN 20kΩ sur ADC ===
  - platform: resistance
    id: res_ntc
    sensor: adc_ctn
    configuration: DOWNSTREAM
    resistor: 20kOhm
    reference_voltage: 3.3


# Sortie PWM pour le chauffage
output:
  - platform: ledc
    pin: GPIO23
    frequency: 1000 Hz
    id: pwm_heater

# Example configuration entry
climate:
  - platform: pid
    name: "PID Climate Controller"
    sensor: temp_ds18b20
    default_target_temperature: 1°C
   
    heat_output: pwm_heater
    control_parameters:
      kp: 0.49460
      ki: 0.00487
      kd: 12.56301
      output_averaging_samples: 5      # smooth the output over 5 samples
      derivative_averaging_samples: 5  # smooth the derivative value over 10 samples
    deadband_parameters:
      threshold_high: 0.5°C       # deadband within +/-0.5°C of target_temperature
      threshold_low: -0.5°C
 
#light:
#  - platform: monochromatic
#    output: pwm_heater
#    id: sortie_mofset
#    name: "Sortie Mofset"


