substitutions:
  device_name: esp171-clarinette-chauffage-sud
  friendly_name: esp171
  adress_ip: "192.168.0.171"
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  
esp8266:
  board: esp12e


# Utilisez la LED bleue de l'appareil comme LED d'état, qui clignotera s'il y a des avertissements (lent) ou des erreurs (rapide)
status_led:
  pin:
    number: GPIO5
    inverted: True  

wifi:
  networks:
    - ssid: !secret wifi_esp
      password: !secret mdpwifi_esp
      priority: 1
    - ssid: !secret wifi
      password: !secret mdpwifi
      priority: 0
  reboot_timeout: 5min

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome
web_server:
  port: 80

binary_sensor:
#Etat de la connection
  - platform: status
    name: "${friendly_name}_Status"
    
switch:
  - platform: gpio
    name: "${friendly_name} Rel Chauf Chambre Parents"
    pin: GPIO16
    id: relais1
  - platform: gpio
    name: "${friendly_name} Rel Chauf Chambre Sud"
    pin: GPIO14
    id: relais2
  - platform: gpio
    name: "${friendly_name} Relais3"
    pin: GPIO12
    id: relais3
  - platform: gpio
    name: "${friendly_name} Relais4"
    pin: GPIO13
    id: relais4
