substitutions:
  device_name: esp173-cpt-eau-piscine
  adress_ip: "192.168.0.173"
  friendly_name: esp173
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
esp8266:
  board: d1_mini
  framework:
    version: recommended  

  
wifi:
  networks:
    - ssid: !secret wifi
      password: !secret mdpwifi
  reboot_timeout: 5min
  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0
    dns1: 192.168.0.192
    dns2: 192.168.0.37

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:

ota:
  platform: esphome

web_server:
  port: 80

binary_sensor:
#Etat de la connection
  - platform: status
    name: "${friendly_name}_Status"

sensor:
  # USS-HS43TI
  # F(Hz)= 8*flow rate(Q)(l/min)
  # 1L=477Hz,
  # D4

  - platform: pulse_meter
    pin: RX
    name: "Cpt Eau Piscine"
    unit_of_measurement: "litre/mn"
    icon: "mdi:water"

    filters:
      - lambda: return (x/(8*60));
    total:
      name: "Cpt Eau Piscine Total"
      unit_of_measurement: "m³"
      accuracy_decimals: 3
      device_class: water
      state_class: total_increasing
      filters:
        - lambda: return (x/(8*60)/1000);

# Informations WI_FI
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    update_interval: 60s

############### TEMPLATE  ######################"
# 
                    
switch:
  - platform: restart
    name: "Restart"




