substitutions:
  device_name: esp140-chalet-eth
  adress_ip: "192.168.0.140"
  friendly_name: esp140
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP32
  board: esp-wrover-kit

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "7f5924bc7de9aceb5b6b434afab874c4"

web_server:
  port: 80

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  
  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

sensor:
# Mesure du niveau
  - platform: adc
    pin: GPIO39 #A0
    id: niveau_eau
    name: "${friendly_name}_niveau_puit"
    unit_of_measurement: "ml"
    update_interval: 60s
    attenuation: 11db
    filters:
      - calibrate_linear:
         - 0.4 -> 0.0  # 4 ma
         - 1.88 -> 3.23  # 12.61
      - sliding_window_moving_average:
          window_size: 5 # moyenne sur x lectures
          send_every: 5 # envoi toutes les x lectures
          send_first_at: 1 # envoi à la premiere lecture

############### TEMPLATE  ######################"
# Calcul volume eau
  - platform: template
    name: "volume_puit"
    id: volume
    icon: mdi:flash
    unit_of_measurement: "m3"
    accuracy_decimals: 2
    lambda: |-
      return (id(niveau_eau).state*0.6*0.6*3.14159);
      
  - platform: template
    name: "niveau_remplissage_puit"
    id: niveau
    icon: mdi:flash
    unit_of_measurement: "%"
    accuracy_decimals: 2
    lambda: |-
      return (id(niveau_eau).state/5.8*100);

  - platform: template
    name: "niveau_reserve_puit"
    id: niveau_reserve
    icon: mdi:flash
    unit_of_measurement: "m"
    accuracy_decimals: 2
    lambda: |-
      return (5.8-id(niveau_eau).state);

#Etat de la connection
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

switch:   
  - platform: restart
    name: "${friendly_name} Restart"
    

    