substitutions:
  device_name: "esp177-esp32-test-ble"
  friendly_name: esp177
  adress_ip: "192.168.0.177"
  time_timezone: "Europe/Paris"

esphome:
  name: ${device_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: debug
# Enable Home Assistant API
api:
ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

web_server:
  port: 80

captive_portal:
  
# Configuration detecteur ouverture BLE
esp32_ble_tracker:
  scan_parameters:
    interval: 10ms
    window: 10ms
    active: false

xiaomi_rtcgq02lm:
  - id: ouv2
    mac_address: "E4:AA:EC:35:09:66"
    bindkey: "556ecfc7f5974b540a6650816486dd9c"

binary_sensor:
  - platform: xiaomi_rtcgq02lm
    id: ouv2
    motion:
      name: "Mi Motion"
    light:
      name: "Mi Motion Sensor Light"
    button:
      name: "Mi Motion Sensor Button"

sensor:
  - platform: xiaomi_rtcgq02lm
    id: ouv2
    battery_level:
      name: "Mi Motion Sensor Battery Level"      