# https://grok.com/share/bGVnYWN5_6ff24576-1c6b-4186-a278-3d7fcba41b61

substitutions:
  device_name: "esp181-ecran-tactile1"
  friendly_name: esp181
  adress_ip: "192.168.0.181"
  time_timezone: "Europe/Paris"

esphome:
  name: ${device_name}
  project:
    name: "rem81.esp181-esp32"
    version: "0.0.0"

esp32:
  board: lolin32
  framework:
    type: arduino

wifi:
  networks:
    - ssid: !secret wifi
      password: !secret mdpwifi
  reboot_timeout: 5min
  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

logger:
  level: DEBUG

ota:
  platform: esphome

api:

# Activer SPI
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

# Configuration de l'écran
display:
  - platform: ili9xxx
    model: ILI9341
    id: my_display
    color_palette: 8BIT
    cs_pin: GPIO15
    dc_pin: GPIO5
    reset_pin: GPIO4
    rotation: 90
    invert_colors: false
    dimensions:
      width: 320
      height: 240
# Example configuration entry
lvgl:
  displays:
    - my_display
  pages:
    - id: main_page
      widgets:
        - label:
            align: CENTER
            text: 'Hello World!'