substitutions:
  device_name: esp173-dimmer
  adress_ip: "192.168.0.173"
  friendly_name: esp173
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  includes:
    - my_output0.h
  libraries:
    - RBDdimmer

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  networks:

    - ssid: !secret wifi_esp
      password: !secret mdpwifi_esp
      priority: 1
    - ssid: !secret wifi
      password: !secret mdpwifi
      priority: 0

  reboot_timeout: 5min
  
  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

captive_portal:

output:
- platform: custom
  type: float
  lambda: |-
    auto my_custom_float_output = new MyCustomFloatOutput();
    App.register_component(my_custom_float_output);
    return {my_custom_float_output};

  outputs:
    id: custom_float

number:
  - platform: template
    name: "Template number"
    optimistic: true
    min_value: 0
    max_value: 100
    step: 1
    on_value:
      then:
        - output.set_level:
            id: custom_float
            level: 10%