esphome:
  name: test-dimmer
  includes:
    - my_custom_component.h
  libraries:
    - RBDdimmer

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Dimmer Fallback Hotspot"
    password: "qAnOBFfF5ilB"

captive_portal:



custom_component:
- lambda: |-
    auto my_custom = new MyCustomComponent();
    return {my_custom};