input_boolean:
  # Validation notification alerte météo 
  stop_notif_previ_pluie:
    name: Stop Notif Previ Pluie

  com_vp2:
    name: Comm VP2 OK=On


sensor:
# Vantage Pro2 -> WEEXWX
  - platform: mqtt
    name: "VP2_DateTime"
    unique_id: VP2_DateTime" 
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'ms'
    value_template: "{{ value_json.dateTime | round(1) }}"

  - platform: mqtt
    name: "VP2_Temp_Out"
    unique_id: "VP2_Temp_Out"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: '°C'
    value_template: "{{ value_json.outTemp_C | round(1) }}"
    device_class: "temperature"

  - platform: mqtt
    name: "VP2_Humidity_Out"
    unique_id: "VP2_Humidity_Out"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: '%'
    value_template: "{{ value_json.outHumidity | round(1) }}"
    device_class: humidity
        

  - platform: mqtt
    name: "VP2_Barometer"
    unique_id: "VP2_Barometer"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'mbar'
    value_template: "{{ value_json.barometer_mbar | round(1) }}"
    device_class: "pressure"
    
#DAILY RAIN (PRECIPITATION QUOTIDIENNE).
#Appuyez sur RAINDAY pour afficher la pluviométrie cumulée depuis minuit.
#Toutes les précipitations cumulées depuis les 24 dernières heures sont affichées dans le bandeau déroulant au bas de l'écran.
  - platform: mqtt
    name: "VP2_Rain"
    unique_id: "VP2_Rain"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'mm'
    force_update: true
    value_template: >-
      {% set a=value_json.rain_cm|float(default=0)%}
      {{ (a*10)|round(3) }}     

  - platform: mqtt
    name: "VP2_Rain24"
    unique_id: "VP2_Rain24"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'mm'
    force_update: true
    value_template: >-
      {% set a=value_json.rain24_cm|float(default=0)%}
      {{ (a*10)|round(3) }}

# La Rain Rate (pluviométrie) sera nulle et l'icône parapluie ne sera pas affichée tant que
# deux basculements du pluviomètre ne sont pas survenus dans une période de 15 minutes.
  - platform: mqtt
    name: "VP2_Rain_Rate"
    unique_id: "VP2_Rain_Rate"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'mm/h'
    force_update: true
    value_template: >-
      {% set a=value_json.rainRate_cm_per_hour|float(default=0)%}
      {{ (a*10)|round(3) }}

#RAIN STORM (AVERSE D'ORAGE).
#Rain Storm (L'averse d'orage) affiche le cumul de pluie de la dernière averse.
#Il faut deux basculements du pluviomètre pour démarrer un événement d'orage et 24 heures sans pluie pour le stopper.
#Appuyez sur RAINDAY pour basculer entre les précipitations quotidiennes et le total d'Averse d'orage.
#Le cumul de pluie peut être affiché en pouces (in) ou millimètres (mm).    
  - platform: mqtt
    name: "VP2_Rain_Storm"
    unique_id: "VP2_Rain_Storm"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'mm'
    force_update: true
    value_template: >-
      {% set a=value_json.stormRain_cm|float(default=0)%}
      {{ (a*10)|round(3) }}

  - platform: mqtt
    name: "VP2_Rafale"
    unique_id: "VP2_Rafale"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'km/h'
    value_template: "{{ value_json.windGust_kph | round(2) }}"

  - platform: mqtt
    name: "VP2_Win_Speed"
    unique_id: "VP2_Win_Speed"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'km/h'
    value_template: "{{ value_json.windSpeed_kph | round(2) }}"

  - platform: mqtt
    name: "VP2_Win_Dir"
    unique_id: "VP2_Win_Dir"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: '°'
    value_template: "{{ value_json.windDir | round(1) }}"

  - platform: mqtt
    name: "VP2_Temp_In"
    unique_id: "VP2_Temp_In"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: '°C'
    value_template: "{{ value_json.inTemp_C | round(1) }}"
    device_class: "temperature"

  - platform: mqtt
    name: "VP2_Humidté_In"
    unique_id: "VP2_Humidté_In"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: '%'
    value_template: "{{ value_json.inHumidity | round(1) }}"
    device_class: "humidity"

  - platform: mqtt
    name: "VP2_Ressenti"
    unique_id: "VP2_Ressenti"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: '°C'
    value_template: "{{ value_json.windchill_C | round(1) }}"
    device_class: "temperature"

  - platform: mqtt
    name: "VP2_HeatIndex"
    unique_id: "VP2_HeatIndex"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: '°C'
    value_template: "{{ value_json.heatindex_C | round(1) }}"
    device_class: "temperature"

  - platform: mqtt
    name: "VP2_Radiation"
    unique_id: "VP2_Radiation"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'W/m²'
    value_template: "{{ value_json.radiation_Wpm2 | round(0) }}"

  - platform: mqtt
    name: "VP2_UV"
    unique_id: "VP2_UV"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'UV'
    value_template: "{{ value_json.UV | round(1) }}"

# lune https://www.home-assistant.io/integrations/moon/
  - platform: moon

  - platform: season  

  - platform: template
    sensors:
# Azimuth et elevation soleil sont aussi calculés dans ESP134 mais sujet à coupure
      sun_elevation:
        friendly_name: 'elevation soleil'
        unit_of_measurement: "°"
        value_template: "{{'%+.1f'|format(state_attr('sun.sun', 'elevation'))}}"

      sun_azimuth:
        friendly_name: 'azimut soleil'
        unit_of_measurement: "°"
        value_template: "{{'%+.1f'|format(state_attr('sun.sun', 'azimuth'))}}"

# calcul de l'heure lever et coucher du soleil
      heure_leve_soleil:
        friendly_name: 'heure_leve_soleil'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%H %M')}}
        icon_template: mdi:weather-sunset-up

      heure_couche_soleil:
        friendly_name: 'heure_couche_soleil'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom(' %H %M')}}
        icon_template: mdi:weather-sunset-down


# Prevision Pluie
#      h_arrivee_pluie:
#        friendly_name: 'Heure arrivée de la Pluie'
#        value_template: >
#          {{ as_timestamp(states('sensor.albi_next_rain')) | timestamp_custom('%H:%M') }}

# Direction du vent
      vp2_direction_du_vent:
        friendly_name: "Vp2 Direction Du vent"
        unique_id: "vp2_direction_du_vent"
        #unit_of_measurement: 'card'
        value_template: >
          {% set dv=state_attr('weather.albi','wind_bearing')|float(default=0)%}
          {% if dv<11 %}
            {{'N'}}
          {% elif dv<34 %}
            {{'NNE'}}
          {% elif dv<57 %}
            {{'NE'}}
          {% elif dv<79 %}
            {{'ENE'}}
          {% elif dv<101 %}
            {{'E'}}
          {% elif dv<124 %}
            {{'ESE'}}
          {% elif dv<146 %}
            {{'SE'}}
          {% elif dv<169 %}
            {{'SSE'}}
          {% elif dv<191 %}
            {{'S'}}
          {% elif dv<214 %}
            {{'SSO'}}
          {% elif dv<236 %}
            {{'SO'}}
          {% elif dv<259 %}
            {{'OSO'}}
          {% elif dv<281 %}
            {{'O'}}
          {% elif dv<304 %}
            {{'ONO'}}
          {% elif dv<326 %}
            {{'NO'}}
          {% elif dv<349 %}
            {{'NNO'}}
          {% else %}
            {{'N'}}
          {%endif%}


# Integration Amber -> Pollen

      grass_pollen_index_mod:
        friendly_name: Pollen Grass Amber
        icon_template: 'mdi:flower'
        value_template: >-
          {% if is_state('sensor.pollen_grass_risk', 'low') %}
            0
          {% elif is_state('sensor.pollen_grass_risk','moderate') %}
            1
          {% elif is_state('sensor.pollen_grass_risk','high') %}
            2
          {% elif is_state('sensor.pollen_grass_risk','very_high') %}
            3
          {% else %}
            Unknown
          {% endif %}

      tree_pollen_index_mod:
        friendly_name: Pollen Tree Amber
        icon_template: 'mdi:tree'
        value_template: >-
          {% if is_state('sensor.pollen_tree_risk', 'low') %}
            0
          {% elif is_state('sensor.pollen_tree_risk','moderate') %}
            1
          {% elif is_state('sensor.pollen_tree_risk','high') %}
            2
          {% elif is_state('sensor.pollen_tree_risk','very_high') %}
            3
          {% else %}
            Unknown
          {% endif %}     

      weed_pollen_index_mod:
        friendly_name: Pollen Weed Amber
        icon_template: 'mdi:sprout'
        value_template: >-
          {% if is_state('sensor.pollen_weed_risk', 'low') %}
            0
          {% elif is_state('sensor.pollen_weed_risk','moderate') %}
            1
          {% elif is_state('sensor.pollen_weed_risk','high') %}
            2
          {% elif is_state('sensor.pollen_weed_risk','very_high') %}
            3
          {% else %}
            Unknown
          {% endif %}


# Integration Météo France

      mf_temperature:
        value_template: >-
          {{ state_attr('weather.albi','temperature') }}
        unit_of_measurement: °C

      mf_humidity:
        value_template: >-
          {{ state_attr('weather.albi','humidity') }}

      mf_pressure:
        value_template: >-
          {{ state_attr('weather.albi','pressure') }}
        unit_of_measurement: hPa

      mf_current_conditions:
        value_template: >-
          {{ states.weather.albi.state }}

  #        feels_like
      mf_visibility:
        value_template: >-
          {{state_attr('weather.albi','visibility') }}
      
      mf_wind_bearing:
        value_template: >-
          {{state_attr('weather.albi','wind_bearing') }}
        # {{states('sensor.vp2_win_dir')}}

      mf_wind_speed:
        value_template: >-
          {{ state_attr('weather.albi','wind_speed') }}

      mf_o3:
        value_template: >-
          {{ state_attr('weather.albi','ozone') }}
        
      mf_weather_condition_0d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[0].condition  }}
      mf_weather_condition_1d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[1].condition }}
      mf_weather_condition_2d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[2].condition }}
      mf_weather_condition_3d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[3].condition  }}
      mf_weather_condition_4d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[4].condition  }}

      mf_temperature_maximum_0d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[0].temperature }}
        unit_of_measurement: °C
      mf_temperature_maximum_1d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[1].temperature }}
        unit_of_measurement: °C
      mf_temperature_maximum_2d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[2].temperature }}
        unit_of_measurement: °C
      mf_temperature_maximum_3d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[3].temperature }}
        unit_of_measurement: °C
      mf_temperature_maximum_4d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[4].temperature }}
        unit_of_measurement: °C
        
      mf_temperature_minimum_0d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[0].templow }}
        unit_of_measurement: °C
      mf_temperature_minimum_1d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[1].templow }}
        unit_of_measurement: °C        
      mf_temperature_minimum_2d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[2].templow }}
        unit_of_measurement: °C
      mf_temperature_minimum_3d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[3].templow }}
        unit_of_measurement: °C
      mf_temperature_minimum_4d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[4].templow }}
        unit_of_measurement: °C

      mf_precipitation_intensity_0d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[0].precipitation }}

      mf_precipitation_probability_0d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[0].precipitation }}

      mf_precipitation_probability_1d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[1].precipitation }}

      mf_precipitation_probability_2d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[2].precipitation }}

      mf_precipitation_probability_3d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[3].precipitation }}

      mf_precipitation_probability_4d:
        value_template: >-
          {{ state_attr('weather.albi','forecast')[4].precipitation }}

# Meteo france

      meteo_france_orage:
        friendly_name: Orages
        value_template: '{{ state_attr(''sensor.81_weather_alert'', ''Orages'') }}'
      meteo_france_inondation:
        friendly_name: Inondation
        value_template: '{{ state_attr(''sensor.81_weather_alert'', ''Inondation'') }}'
      meteo_france_pluie_inondation:
        friendly_name: Inondation
        value_template: '{{ state_attr(''sensor.81_weather_alert'', ''Pluie-inondation'') }}'       
      meteo_france_vague:
        friendly_name: Vagues-submersion
        value_template: '{{ state_attr(''sensor.81_weather_alert'', ''Grand-froid'') }}'         
      meteo_france_vent:
        friendly_name: Vent violent
        value_template: '{{ state_attr(''sensor.81_weather_alert'', ''Vent violent'') }}'          
      meteo_france_neige:
        friendly_name: Neige-verglas
        value_template: '{{ state_attr(''sensor.81_weather_alert'', ''Neige-verglas'') }}'        

      meteo_france_temperature_maximale_pour_demain:
        friendly_name: Prévision température maximale
        value_template: >-
          {% set start = (now().replace(hour=0,minute=0,second=0)) %}
          {% set end = (start + timedelta(days=2)) %}
          {{ state_attr('weather.albi', 'forecast') | selectattr('datetime', '>', start) | selectattr('datetime','<=', end) | map(attribute='temperature') | list | max }}     
        unit_of_measurement: '°C'      

      meteo_france_temperature_minimale_pour_demain:
        friendly_name: Prévision température minimale
        value_template: >-
          {% set start = (now().replace(hour=0,minute=0,second=0)) %}
          {% set end = (start + timedelta(days=2)) %}
          {{ state_attr('weather.albi', 'forecast') | selectattr('datetime', '>=', start) | selectattr('datetime','<=', end) | map(attribute='templow') | list | max }} 
        unit_of_measurement: '°C'      

      today_icon:
          value_template: >-
            {% if state_attr("weather.albi","forecast")[0].condition =='clear-night' %}
              3
            {% elif state_attr("weather.albi","forecast")[0].condition =='cloudy' %}
              5
            {% elif state_attr("weather.albi","forecast")[0].condition =='fog' %}
              16
            {% elif state_attr("weather.albi","forecast")[0].condition =='hail' %}
              6
            {% elif state_attr("weather.albi","forecast")[0].condition =='lightning' %}
              13
            {% elif state_attr("weather.albi","forecast")[0].condition =='lightning-rainy' %}
              17
            {% elif state_attr("weather.albi","forecast")[0].condition =='partlycloudy' %}
              8
            {% elif state_attr("weather.albi","forecast")[0].condition =='pouring' %}
              18
            {% elif state_attr("weather.albi","forecast")[0].condition =='rainy' %}
              9
            {% elif state_attr("weather.albi","forecast")[0].condition =='snowy' %}
              11
            {% elif state_attr("weather.albi","forecast")[0].condition =='snowy-rainy' %}
              7
            {% elif state_attr("weather.albi","forecast")[0].condition =='windy' %}
              14
            {% elif state_attr("weather.albi","forecast")[0].condition =='windy-variant' %}
              14
            {% else %}
              12
            {% endif %}
          friendly_name: Today weather forecast  

# Statistiques
  # Pluviometrie - sert à gestion robot tonte
  - platform: statistics
    entity_id: sensor.vp2_rain24
    unique_id: vp2_pluviometrie_min
    max_age:
      minutes: 320 # sur 6h
    name: vp2_pluviometrie_min
    state_characteristic: value_min

  - platform: statistics
    entity_id: sensor.vp2_rain24
    unique_id: vp2_pluviometrie_max
    max_age:
      minutes: 320 # sur 6h
    name: vp2_pluviometrie_max
    state_characteristic: value_max

  - platform: statistics
    entity_id: sensor.vp2_rain24
    unique_id: vp2_pluviometrie_moyenne
    max_age:
      minutes: 320 # sur 6h
    name: vp2_pluviometrie_moyenne
    state_characteristic: median

  - platform: statistics
    entity_id: sensor.vp2_rain24
    unique_id: vp2_pluviometrie_standard_deviation
    max_age:
      minutes: 320 # sur 6h
    name: vp2_pluviometrie_standard_deviation
    state_characteristic: standard_deviation

  # Vents
  - platform: statistics
    entity_id: sensor.vp2_rafale
    unique_id: vp2_rafales_max
    max_age:
      minutes: 1660 # sur 24h
    name: vp2_rafales_max
    state_characteristic: value_max
    
  # Ensoleillement
  - platform: statistics
    entity_id: sensor.vp2_radiation
    unique_id: vp2_radiation_moyenne
    max_age:
      minutes: 60 # sur 1h
    name: vp2_radiation_moyenne
    state_characteristic: median

