####################################################
#                                                  #
#                     RESEAUX                      #
#                                                  #
####################################################

binary_sensor:

  - platform: ping
    host: 192.168.0.14
    name: "ping_pc_motion"

#  - platform: ping
#    host: 192.168.0.21
#    name: "ping_cam_terrasse"

  - platform: ping
    host: 192.168.0.25
    name: "ping_RPI ADguard"

  - platform: ping
    host: 192.168.0.26
    name: "ping_ECO COMPTEUR"

  - platform: ping
    host: 192.168.0.36
    name: "ping_cam_cuisine"

  - platform: ping
    host: 192.168.0.39
    name: "ping_cam_garage_ext"

  - platform: ping
    host: 192.168.0.47
    name: "ping_Module Adam"

  - platform: ping
    host: 192.168.0.50
    name: "ping_routeur dlink"

  - platform: ping
    host: 192.168.0.54
    name: "ping_cam_salon"

  - platform: ping
    host: 192.168.0.56
    name: "ping_cam_sous_sol"

  - platform: ping
    host: 192.168.0.57
    name: "ping_cam_garage_int"

  - platform: ping
    host: 192.168.0.61
    name: "ping_cam_piscine"

  - platform: ping
    host: 192.168.0.62
    name: "ping_RPI Weewx"

  - platform: ping
    host: 192.168.0.101
    name: "ping_Module Wago Piscine"

#  - platform: ping
#    host: 192.168.0.121
#    name: "ping_Arduino Piscine"

  - platform: group
    name: ping_reseau
    all: true
    device_class: "connectivity"
    entities:
      - binary_sensor.ping_rpi_adguard
      - binary_sensor.ping_module_adam
      - binary_sensor.ping_module_wago_piscine
      - binary_sensor.ping_routeur_dlink
      - binary_sensor.ping_eco_compteur      
      - binary_sensor.ping_cam_cuisine
      - binary_sensor.ping_cam_garage_ext
      - binary_sensor.ping_cam_garage_int
      - binary_sensor.ping_cam_piscine
      - binary_sensor.ping_cam_salon

  #    - binary_sensor.cam_terrasse    

  - platform: group
    name: esp_reseau
    all: true
    device_class: "connectivity"
    entities:
      - binary_sensor.esp123_status
      - binary_sensor.esp124_status
      - binary_sensor.esp125_status
      - binary_sensor.esp129_status
      - binary_sensor.esp130_status
      - binary_sensor.esp132_status
      - binary_sensor.esp133_status
      - binary_sensor.esp135_status
      - binary_sensor.esp137_status
      - binary_sensor.esp138_status
      - binary_sensor.esp139_status
      - binary_sensor.esp140_status
      - binary_sensor.esp142_status
      - binary_sensor.test_reseau

  - platform: group
    name: uptime_reseau
    all: true
    device_class: "connectivity"
    entities:
      - binary_sensor.uptime_domo_rem81
      - binary_sensor.uptime_jeedom
      - binary_sensor.uptime_meteo81000
      - binary_sensor.uptime_meteoweewx
      - binary_sensor.uptime_ha
      - binary_sensor.uptime_motioneye
      - binary_sensor.uptime_vtt
      - binary_sensor.uptime_kobold






