####################################################
#                                                  #
#                     SYSTEME                      #
#                                                  #
####################################################
input_boolean:
  alim_tablette_ok:
    name: Alim Tablette OK=On


  # https://forum.hacf.fr/t/scan-interval-dun-sensor-command-line/5182
  #- platform: command_line
  #  name: "Portainer Online"
  #  command: response=$(curl -LIk -m 3 http://192.168.0.153:9000 -o /dev/null -w "%{http_code}\n" -s); test "$response" -ge 200 && echo "Online" || echo "Offline"
  #  scan_interval: 90
  #  value_template: "{{ value }}"

     
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'



