input_boolean:
  # Gestion volets
  presence_amis_bureau:
    name: Presence Amis Bureau
    icon: mdi:account

  presence_amis_ch_sud:
    name: Presence Amis Chamb Sud
    icon: mdi:account

  presence_amis_ch_nord:
    name: Presence Amis Chamb Nord
    icon: mdi:account

# Calcul Jour/nuit selon luminosite et position du soleil sur l'horizon
  nuit_jour:
    name: Nuit=0/Jour=1
    icon: mdi:weather-sunny

input_datetime:
  # Horaires Volets ete
  horaire_ete_volet_ouv:
    name: Horaire ete volets ouverture
    has_date: false
    has_time: true
  horaire_ete_volet_ferm:
    name: Horaire ete volets fermeture
    has_date: false
    has_time: true
  # Horaires Volets hiver
  horaire_hiver_volet_ouv:
    name: Horaire hiver volets ouverture
    has_date: false
    has_time: true

# Horaire surveillance porte
  heure_debut_alarme_porte:
    name: Heure debut alarme portes
    has_date: false
    has_time: true
  heure_fin_alarme_porte:
    name: Heure fin alarme portes
    has_date: false
    has_time: true


input_number:
# Consigne Min/max luminosité 
# gestion volet: Calcul du Input_boolean Nuit/jout
    luminosite_seuil_bas:
      name: Lum. seuil bas
      mode: box
      min: 0
      max: 10
      unit_of_measurement: "Lux"
      icon: mdi:weather-sunny
    luminosite_seuil_haut:
      name: Lum. seuil haut
      mode: box
      min: 10
      max: 50
      unit_of_measurement: "Lux"
      icon: mdi:weather-sunny 

binary_sensor:
#inversion d'état pour l'alarme ALARMO
  - platform: template
    sensors:
      porte_garage_non_fermee:
        value_template: >-
          {% if is_state('binary_sensor.porte_garage_fermee', 'on') %}
            off
          {% else %}
            on
          {% endif %} 
      porte_ssol_non_fermee:
        value_template: >-
          {% if is_state('binary_sensor.porte_ssol_fermee', 'on') %}
            off
          {% else %}
            on
          {% endif %} 

input_select:
  volets:
    name: Volets
    icon: mdi:window-shutter
    options:
      - Auto Hiv
      - Auto Ete
      - Auto Pos Soleil
      - Absent
      - Arret

cover:
# Volets Proportionnels
# Porte Sous Sol
  - platform: cover_rf_time_based
    devices:
      porte_sous_sol:
        name: Porte sous sol
        travelling_time_up: 21
        travelling_time_down: 21
        close_script_entity_id: script.porte_sous_sol_down
        stop_script_entity_id: script.porte_sous_sol_stop
        open_script_entity_id: script.porte_sous_sol_up
        device_class: garage
        always_confident: True

# Porte garage
  - platform: cover_rf_time_based
    devices:
      porte_garage:
        name: Porte garage
        travelling_time_up: 21
        travelling_time_down: 21
        close_script_entity_id: script.porte_garage_down
        stop_script_entity_id: script.porte_garage_stop
        open_script_entity_id: script.porte_garage_up
        device_class: garage
        always_confident: True

# Ch amis sud
  - platform: cover_rf_time_based
    devices:
      volet_amis_sud_proport:
        name: Volet amis sud P
        travelling_time_up: 21
        travelling_time_down: 19
        close_script_entity_id: script.volet_amis_sud_down
        stop_script_entity_id: script.volet_amis_sud_grand_stop_2
        open_script_entity_id: script.volet_amis_sud_up
        always_confident: True


