####################################################
#                                                  #
#                         WC                       #
#                                                  #
####################################################


utility_meter:
# usage jour  
  energy_wc_usage_daily:
    source: sensor.energy_pc_wc
    cycle: daily
    tariffs:
      - hp
      - hc

template:
# Consommation HP + HC - addition des utility meter
  - sensor:
    - name: "Energie WC Jour"
      unique_id: "energy_wc_daily"
      state: >-
        {% set p = states('sensor.energy_wc_usage_daily_hp') | float(default=0) | round(2) %}
        {% set o = states('sensor.energy_wc_usage_daily_hc') | float(default=0) | round(2) %}
        {{ (o + p) | round(2) }}
      unit_of_measurement: "kWh"
      device_class: "energy"
      state_class: "total"  

sensor:
# Energie WC
  - platform: integration
    source: sensor.ecocompteur_wc
    name: energy_pc_wc
    unit_prefix: k
    method: left
    round: 2
