---
# Basic switch or light state
# vars:
#   uid: <unique identifer for the switch. Must match the ID of the button>
#   entity_id: <Home Assistant entity_id for the object we are controlling>

binary_sensor:
  - id: widget_sensor_${uid}
    platform: homeassistant
    entity_id: ${entity_id}
    publish_initial_state: true
    on_state:
      - if:
          condition:
            - binary_sensor.is_on: widget_sensor_${uid}
          then:
            - lvgl.widget.update:
                id: button_${uid}
                bg_color: $button_on_color
            - lvgl.widget.update:
                id: icon_${uid}
                text_color: $icon_on_color
            - lvgl.widget.update:
                id: label_${uid}
                text_color: $label_on_color
          else:
            - lvgl.widget.update:
                id: button_${uid}
                bg_color: $button_off_color
            - lvgl.widget.update:
                id: icon_${uid}
                text_color: $icon_off_color
            - lvgl.widget.update:
                id: label_${uid}
                text_color: $label_off_color
